### ISSUE TITLE
Add timedelta support

### ISSUE THREAD

**Issue by lannuttia** [zifeo/dataconf#133]
I think it would be really useful if this library was able to support [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations). I know that [Pydantic](https://docs.pydantic.dev/latest/api/standard_library_types/#datetimetimedelta) supports converting an ISO 8601 Duration to a timedelta. Unfortunately, it appears that I am not actually able to get Pydantic to handle the ISO 8601 duration to timedelta conversion without this library trying to do the conversion and failing because it doesn't know how to make an ISO 8601 duration to a timedelta. I think this might be solvable by either making this library aware that a dataclass is a pydantic dataclass instead of a standard dataclass and disabling this libraries translation on it or just outright adding ISO 8601 duration translation support to this library.

**Comment by zifeo** [comment]
@lannuttia I believe the latter is the best choice and should be rather easy to implement. Wanna give it a try?

**Comment by lannuttia** [comment]
I have added support for this and have opened #134. Please let me know if there is anything else that needs to be done here before this can be merged.

**Comment by zifeo** [comment]
Released in https://github.com/zifeo/dataconf/releases/tag/v2.5.0
