### ISSUE TITLE
Dependency Conflict When Attempting to Use With Moto

### ISSUE THREAD

**Issue by lannuttia** [zifeo/dataconf#144]
I am attempting to use this library alongside `moto[glue] ~= 5.0` and am getting the following error:

```
ERROR: Cannot install dataconf==2.5.0 and moto[glue]==5.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    moto[glue] 5.0.0 depends on pyparsing>=3.0.7; extra == "glue"
    dataconf 2.5.0 depends on pyparsing==2.4.7

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

This should be something that could be resolved by updating this project to `pyparsing ~= 3.1`

**Comment by zifeo** [comment]
@lannuttia thanks for reporting, sadly the pyparsing upgrade does not seem to go well with pyhocon, see the issues [list](https://github.com/chimpler/pyhocon/issues). Maybe there is a way to make it work without having breaking change but all previous attempt failed. There might be also a chance to allow dependency override but did not look into it. I would encourage you to give it a try :)

**Comment by lannuttia** [comment]
I have created the following PR: #145

In order to upgrade everything I had to update a single test in a way that makes me slightly uneasy but I figured I'd send it your way and let you judge whether we should pursue the issue further or if it's good to ship as is.

**Comment by lannuttia** [comment]
I have created an issue against pyhocon [here](https://github.com/chimpler/pyhocon/issues/324).

**Comment by zifeo** [comment]
@lannuttia v3.0.0 has been released with your fix, let see whether there are other breakage report.
