### ISSUE TITLE
Add support for tuple types

### ISSUE THREAD

**Issue by lannuttia** [zifeo/dataconf#147]
It appears that dataconf does not support tuple types. This is an issue in the case that you want to pass a frozen dataclass instance created by dataconf into a function decorated with `@functools.cache` because lists are not hashable. I think that adding support for tuples would allow for the creation of frozen dataclass instances that are hashable because all of the fields within the dataclass would be hashable themselves.

**Comment by lannuttia** [comment]
I have created a PR that should add support for dataclasses with tuple values. If anything else needs to be done here, please feel free to let me know.

**Comment by zifeo** [comment]
Released in v3.1.0.
