### ISSUE TITLE
Python 3.10 Import error with collections

### ISSUE THREAD

**Issue by dwsmith1983** [zifeo/dataconf#27]
With Python 3.10, we encounter an import error related to collections.

Similar issues:
https://github.com/rmartin16/qbittorrent-api/issues/45
https://github.com/carbonblack/cbapi-python/issues/298

```
[ImportError]
cannot import name 'Mapping' from 'collections' (/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/collections/__init__.py)
```

From [this issue](https://github.com/rmartin16/qbittorrent-api), they found an issue with 

```
*rmartin Feb 2021
AttrDict finally broke with Python 3.10 since abstract base classes can no
longer be imported from collections but should use collections.abc instead.
Since AttrDict is abandoned, I've consolidated the code here for future use.
AttrMap and AttrDefault are left for posterity but commented out.
"""

from abc import ABCMeta
from abc import abstractmethod
from re import match as re_match

try:  # python 3
    from collections.abc import Mapping
    from collections.abc import MutableMapping
    from collections.abc import Sequence
except ImportError:  # python 2
    from collections import Mapping
    from collections import MutableMapping
    from collections import Sequence
```

**Comment by pirofti** [comment]
I have also ran into this issue and decided to fix this and release it on PyPI as [AttrDict3](https://pypi.org/project/attrdict3/). Feel free to use it or open issues on the [forked repository](https://github.com/pirofti/AttrDict3). After install, you should not have to modify anything in your code-base.
