### ISSUE TITLE
Support mypy imports

### ISSUE THREAD

**Issue by kavinvin** [zifeo/dataconf#37]
## Description
`mypy` report error when importing `dataconf`

## Expected Behavior
`mypy` checks pass without any error without  the need to use `ignore_missing_imports = True` option

## Actual Behavior
```
error: Skipping analyzing "dataconf": module is installed, but missing library stubs or py.typed marker  [import]
```

**Comment by zifeo** [comment]
@kavinvin This should be fixed in 1.4.0, can you confirm and give us an update?

**Comment by kavinvin** [comment]
@zifeo Yes, it solved the issue! Thanks.

**Comment by zifeo** [comment]
@kavinvin Awesome, feel free to give feedback or star the project if it provides you with value.
