### ISSUE TITLE
BUG: typing.Union is accepted with only two params

### ISSUE THREAD

**Issue by janhabersetzer** [zifeo/dataconf#77]
Hi guys,
the following report will refer to this line of code that unpacks typing.Union's arguments (args).
https://github.com/zifeo/dataconf/blob/6c41d3a5d425fb5169e4a77758d72c9b6c79b65b/dataconf/utils.py#L134

**Error**:
If you provide more than two args to typing.Union in a dataclasses.dataclass the parsing of the provided config will raise a "ValueError: too many values to unpack (expected 2)". 
[Expected behaviour of Union](https://docs.python.org/3/library/typing.html#typing.Union) is that you can provide more than two args.

**Example code to face the error**:
One real life example of using more than two args...
```PYTHON
from dataclasses import dataclass
from typing import List, Text, Union
from io import BytesIO
import pandas as pd
from pandas import _typing
import dataconf

PARQUET_PATH = "/path/to/empty.parquet"

str_conf = """
	path = {parquet_path}
""".format(
    length="multi-line", parquet_path=PARQUET_PATH
)


def create_empty_parquet() -> None:
    df = pd.DataFrame()
    df.to_parquet(PARQUET_PATH)


@dataclass
class Parquet:
    # The three args in Union will cause the ValueError
    # Remove the last and it will work
    # Text = classical path
    # ReadBuffer[bytes] = pandas.Buffer
    # BytesIO = used for testing
    path: Union[Text, _typing.ReadBuffer[bytes], BytesIO]
    cols: Union[List[str], None] = None

    def load_df(self) -> pd.DataFrame:
        return pd.read_parquet(path=self.path, columns=self.cols)


create_empty_parquet()
conf = dataconf.loads(str_conf, Parquet)

```

PS: I run Python 3.10

**Comment by dwsmith1983** [comment]
@janhabersetzer Thank you for the feedback and reporting the issue. I will take a look in a bit. I just wanted to acknowledge your submission.

**Comment by dwsmith1983** [comment]
> @dwsmith1983 thank you for letting me know. Looking forward to it! If I can support just let me know.

@janhabersetzer do you have a solution? If so, you can PR it.

**Comment by zifeo** [comment]
Will be fixed in next release, see https://github.com/zifeo/dataconf/pull/92
