### ISSUE TITLE
Possible bug with loader param in `.load` method

### ISSUE THREAD

**Issue by ghost** [zifeo/dataconf#90]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/122423816/234400104-ec8f38c9-5a7b-4de0-8acb-e37140f1c92b.png">

When using `dataconf.load(<file_path>, <clazz>, loader=dataconf.YAML`, the error above is returned. Digging through the lib code, I don't see the kwargs being used to parse or change the loader which might be causing the problem

**Comment by zifeo** [comment]
@FlaglerParth thanks for the report, load is auto-detecting which loader is used based on the file format. We will allow to use the loader parameter to override the automatic detection in the next release, see https://github.com/zifeo/dataconf/pull/92.
