### ISSUE TITLE
Defaults for nested data classes not working?

### ISSUE THREAD

**Issue by jmdacruz** [zifeo/dataconf#97]
Consider the following example:
```python
from dataclasses import dataclass, field
import dataconf


@dataclass
class Nested:
    nested_a: bool = False
    nested_b: str = field(default="")


@dataclass
class TopLevel:
    top_a: str
    top_b: str = field(default="some value")
    top_c: Nested = field(default_factory=Nested)


def main():
    config_string = """
    top_a: "some value"
    top_c: {}
    """
    c1 = dataconf.loads(config_string, TopLevel, loader=dataconf.YAML,
                        ignore_unexpected=True)

    config_string = """
    top_a: "some value"
    """
    c2 = dataconf.loads(config_string, TopLevel, loader=dataconf.YAML,
                        ignore_unexpected=True)

    print(c1, c2)


if __name__ == '__main__':
    main()
```

The first example for `c1` seems to work fine, setting `c1.top_c` to the default value indicated on `Nested`, but the second example of `c2` throws a weird exception:

```
expected type <class '__main__.Nested'> at .top_c, got <class '__main__.Nested'>
 ...
dataconf.exceptions.TypeConfigException: expected type <class '__main__.Nested'> at .top_c, got <class '__main__.Nested'>
```

Which is very confusing, as you can see, because it complains that `__main__.Nested` is not `__main__.Nested`

What am I missing? How should I go about defining nested data classes with default factories?

**Comment by jmdacruz** [comment]
**quick update:** The problem seems to be this line: https://github.com/zifeo/dataconf/blob/7216afaef935cf67155296303776582526b9e668/dataconf/utils.py#L52

That lines says:
```python
if not isinstance(value, ConfigTree):
```

But shouldn't that be this instead?:
```python
if not isinstance(value, clazz):
```

**Comment by zifeo** [comment]
Release in https://github.com/zifeo/dataconf/releases/tag/v2.2.1
